---
- name: Install Apache2 server
  hosts: n1
  become: yes

  tasks:
  - name: Install Apache2
    apt:
      name: apache2
      state: present

  - name: start apache2
    service:
      name: apache2
      state: started

  - name: Enable apache2
    service:
      name: apache2
      enabled: yes  

- name: Install httpd server
  hosts: n1
  become: yes

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present

  - name: start httpd
    service:
      name: httpd
      state: started

  - name: Enable httpd
    service:
      name: httpd
      enabled: yes        
...
